/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as priceFeedRegisterySol from "./PriceFeedRegistery.sol";
export type { priceFeedRegisterySol };
import type * as tFacetSol from "./TFacet.sol";
export type { tFacetSol };
import type * as facets from "./facets";
export type { facets };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Diamond } from "./Diamond";
export type { DiamondCutFacet } from "./DiamondCutFacet";
export type { DiamondGovernance } from "./DiamondGovernance";
export type { PriceAggregator } from "./PriceAggregator";
