/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DCAFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkUpkeep"
      | "executeDCA"
      | "performUpkeep"
      | "setupDCA"
      | "userOrders"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DCAExecuted" | "DCASetup"): EventFragment;

  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeDCA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setupDCA",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userOrders",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executeDCA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setupDCA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userOrders", data: BytesLike): Result;
}

export namespace DCAExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DCASetupEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    interval: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    token: string,
    amount: bigint,
    interval: bigint
  ];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
    interval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DCAFacet extends BaseContract {
  connect(runner?: ContractRunner | null): DCAFacet;
  waitForDeployment(): Promise<this>;

  interface: DCAFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkUpkeep: TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean }],
    "view"
  >;

  executeDCA: TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;

  performUpkeep: TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;

  setupDCA: TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _amount: BigNumberish,
      _interval: BigNumberish,
      _targetPrice: BigNumberish,
      _priceFeed: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  userOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, string] & {
        tokenAddress: string;
        amount: bigint;
        interval: bigint;
        nextExecutionTime: bigint;
        targetPrice: bigint;
        priceFeed: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkUpkeep"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeDCA"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "performUpkeep"
  ): TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setupDCA"
  ): TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _amount: BigNumberish,
      _interval: BigNumberish,
      _targetPrice: BigNumberish,
      _priceFeed: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, string] & {
        tokenAddress: string;
        amount: bigint;
        interval: bigint;
        nextExecutionTime: bigint;
        targetPrice: bigint;
        priceFeed: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DCAExecuted"
  ): TypedContractEvent<
    DCAExecutedEvent.InputTuple,
    DCAExecutedEvent.OutputTuple,
    DCAExecutedEvent.OutputObject
  >;
  getEvent(
    key: "DCASetup"
  ): TypedContractEvent<
    DCASetupEvent.InputTuple,
    DCASetupEvent.OutputTuple,
    DCASetupEvent.OutputObject
  >;

  filters: {
    "DCAExecuted(address,address,uint256)": TypedContractEvent<
      DCAExecutedEvent.InputTuple,
      DCAExecutedEvent.OutputTuple,
      DCAExecutedEvent.OutputObject
    >;
    DCAExecuted: TypedContractEvent<
      DCAExecutedEvent.InputTuple,
      DCAExecutedEvent.OutputTuple,
      DCAExecutedEvent.OutputObject
    >;

    "DCASetup(address,address,uint256,uint256)": TypedContractEvent<
      DCASetupEvent.InputTuple,
      DCASetupEvent.OutputTuple,
      DCASetupEvent.OutputObject
    >;
    DCASetup: TypedContractEvent<
      DCASetupEvent.InputTuple,
      DCASetupEvent.OutputTuple,
      DCASetupEvent.OutputObject
    >;
  };
}
