/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MultiBatchSwapFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DIVISOR"
      | "batchSwapToSingleToken"
      | "batchSwapsToSingleToken"
      | "estimateSwapOutput"
      | "feeBasisPoints"
      | "owner"
      | "renounceOwnership"
      | "setFeeBasisPoints"
      | "transferOwnership"
      | "uniswapFactory"
      | "uniswapRouter"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesCollected"
      | "OwnershipTransferred"
      | "TokensSwapped"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DIVISOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchSwapToSingleToken",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSwapsToSingleToken",
    values: [
      AddressLike[],
      BigNumberish[],
      AddressLike,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateSwapOutput",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeBasisPoints",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeBasisPoints",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DIVISOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSwapToSingleToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSwapsToSingleToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateSwapOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uniswapRouter",
    data: BytesLike
  ): Result;
}

export namespace FeesCollectedEvent {
  export type InputTuple = [collector: AddressLike, feeAmount: BigNumberish];
  export type OutputTuple = [collector: string, feeAmount: bigint];
  export interface OutputObject {
    collector: string;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensSwappedEvent {
  export type InputTuple = [
    user: AddressLike,
    fromToken: AddressLike,
    toToken: AddressLike,
    inputAmount: BigNumberish,
    outputAmount: BigNumberish,
    gasCost: BigNumberish,
    slippage: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    fromToken: string,
    toToken: string,
    inputAmount: bigint,
    outputAmount: bigint,
    gasCost: bigint,
    slippage: bigint
  ];
  export interface OutputObject {
    user: string;
    fromToken: string;
    toToken: string;
    inputAmount: bigint;
    outputAmount: bigint;
    gasCost: bigint;
    slippage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiBatchSwapFacet extends BaseContract {
  connect(runner?: ContractRunner | null): MultiBatchSwapFacet;
  waitForDeployment(): Promise<this>;

  interface: MultiBatchSwapFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DIVISOR: TypedContractMethod<[], [bigint], "view">;

  batchSwapToSingleToken: TypedContractMethod<
    [
      fromToken: AddressLike,
      toToken: AddressLike,
      amount: BigNumberish,
      recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  batchSwapsToSingleToken: TypedContractMethod<
    [
      inputTokens: AddressLike[],
      inputAmounts: BigNumberish[],
      outputToken: AddressLike,
      recipient: AddressLike,
      slippageTolerance: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  estimateSwapOutput: TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, inputAmount: BigNumberish],
    [bigint[]],
    "view"
  >;

  feeBasisPoints: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeBasisPoints: TypedContractMethod<
    [newFeeBPS: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uniswapFactory: TypedContractMethod<[], [string], "view">;

  uniswapRouter: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DIVISOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchSwapToSingleToken"
  ): TypedContractMethod<
    [
      fromToken: AddressLike,
      toToken: AddressLike,
      amount: BigNumberish,
      recipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchSwapsToSingleToken"
  ): TypedContractMethod<
    [
      inputTokens: AddressLike[],
      inputAmounts: BigNumberish[],
      outputToken: AddressLike,
      recipient: AddressLike,
      slippageTolerance: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "estimateSwapOutput"
  ): TypedContractMethod<
    [fromToken: AddressLike, toToken: AddressLike, inputAmount: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "feeBasisPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeBasisPoints"
  ): TypedContractMethod<[newFeeBPS: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uniswapFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "uniswapRouter"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeesCollected"
  ): TypedContractEvent<
    FeesCollectedEvent.InputTuple,
    FeesCollectedEvent.OutputTuple,
    FeesCollectedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokensSwapped"
  ): TypedContractEvent<
    TokensSwappedEvent.InputTuple,
    TokensSwappedEvent.OutputTuple,
    TokensSwappedEvent.OutputObject
  >;

  filters: {
    "FeesCollected(address,uint256)": TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;
    FeesCollected: TypedContractEvent<
      FeesCollectedEvent.InputTuple,
      FeesCollectedEvent.OutputTuple,
      FeesCollectedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokensSwapped(address,address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TokensSwappedEvent.InputTuple,
      TokensSwappedEvent.OutputTuple,
      TokensSwappedEvent.OutputObject
    >;
    TokensSwapped: TypedContractEvent<
      TokensSwappedEvent.InputTuple,
      TokensSwappedEvent.OutputTuple,
      TokensSwappedEvent.OutputObject
    >;
  };
}
